# Generated by Django 5.1.3 on 2024-12-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_article_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image_alt_text",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
